### ISSUE TITLE
ajax request returns the content of the whole page

### ISSUE THREAD

**Issue by format-gmbh** [Zillion01/jpfaq#39]
With the rating function, it doesn't matter if I answer yes or no. As a result, the complete page is displayed below the FAQ answer.

TYPO3 10.4.26
jpfaq 10.4.1
PHP 7.3
jquery 3.4.1/3.6.0

**Comment by format-gmbh** [comment]
The problem was my site-config:
```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      /: 0
      sitemap.xml: 1533906435

```
I had to delete lines 4 and 7. Now it looks like this:
```
RouteEnhancers:
  PageTypeSuffix:
    type: PageType
    index: ''
    map:
      sitemap.xml: 1533906435

```
